### ISSUE TITLE
Support for array of types

### ISSUE THREAD

**Issue by limitlis** [tomarad/JSON-Schema-Instantiator#14]
Hi! 

So in my project we recently started doing something like this: 
`{ type: ['string', 'null'] }`

**For reference:** http://json-schema.org/latest/json-schema-validation.html#anchor79

> 5.5.2.1.  Valid values
> 
> The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.
> 
> String values MUST be one of the seven primitive types defined by the core specification.

I went ahead and did a quick implementation which suits my needs, but not sure if there's a better/ more global solution. 

Since mine basically defaults to the first in the array of types.

Is it worth expanding to maybe support a default value? 

For example: 
`{ type: ['string', 'number', 'null'], default: 100 }`

as long as the default was a type in the list. The type can be inferred and cross-checked against the default value. 

Anyways, I've put up PR for the change that I made. In case you'd like to take a look or suggest a better way of doing it. 
#13

Thanks!

**Comment by limitlis** [comment]
oops, realized later that the `null` in my example has to be a string `'null'`.

**Comment by tomarad** [comment]
Thanks for your contribution!
I'll look into your changes in the next couple of days.

Tom

**Comment by tomarad** [comment]
Merged #13.
