### ISSUE TITLE
Consider not instantiate array items

### ISSUE THREAD

**Issue by henriklundgren** [tomarad/JSON-Schema-Instantiator#15]
I guess without `minItems` it makes little sense to instantiate array items(!?).

Atm the moment I clear the array item,
post instantiating the schema.

**Comment by tomarad** [comment]
Hey,
When I developed this module, instantiating an item of an array in case `minItems` is not defined was necessary for the project I was working on.
It would seem unwise to change what users are already relying on.
My suggestion for you is to fork this repo, and change the following [line](https://github.com/tomarad/JSON-Schema-Instantiator/blob/master/src/instantiator.js#L127
):

From
```javascript
var len = 1;
```

To
```javascript
var len = 0;
```


Tom

**Comment by henriklundgren** [comment]
Ok,
For me its the opposite, I only want array items if the user adds them.
Thanks anyways.
