### ISSUE TITLE
Console Log in index.js file

### ISSUE THREAD

**Issue by will-newmarch** [tomarad/JSON-Schema-Instantiator#22]
https://github.com/tomarad/JSON-Schema-Instantiator/blob/2f6884c79a337d163631cb09493e88d1024c64e1/index.js#L28

**Comment by tomarad** [comment]
Hey :)
Fixed with v0.4.6.

Thanks!
Tom

**Comment by will-newmarch** [comment]
Thanks @tomarad ! :)
