### ISSUE TITLE
Using default value of outer definition

### ISSUE THREAD

**Issue by yoshigev** [tomarad/JSON-Schema-Instantiator#24]
Hi,

If a schema contains a reference to a definition, and only the outer schema has a "default" property, it is not used.
For example:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Parameters",
  "definitions": {
    "Parameters": {
      "type": "object",
      "properties": {
        "enumValue": {
          "$ref": "#/definitions/EnumValue",
          "default": "val_b"
        }
      }
    },
    "EnumValue": {
      "type": "string",
      "enum": [
        "val_a",
        "val_b"
      ]
    }
  }
}
```
Should generate
```
{
  "enumValue": "val_b"
}
```
But actually generates:
```
{
  "enumValue": "val_a"
}
```
If the inner definition contains a default value, it is used correctly.

Thanks.

**Comment by tomarad** [comment]
Hey, thanks for spotting this!
I don't have much time at the moment, could you open a PR to fix this?

Thanks :upside_down_face:

**Comment by tomarad** [comment]
Closed due to inactivity.
