### ISSUE TITLE
Doesn't handle consts correctly

### ISSUE THREAD

**Issue by gamedevsam** [tomarad/JSON-Schema-Instantiator#35]
Given the following schema:

```json
{
      "$id": "entity/user_adult",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": ["type"],
      "properties": {
            "type": { "const": "user_adult" }
      }
}
```

You get an empty object, when it should have:

```json
{
      "type": "user"
}
````

**Comment by tomarad** [comment]
Hey @gamedevsam, thanks! I'll gladly accept a PR that addresses this.

**Comment by gamedevsam** [comment]
Would you be open to a conversion to TypeScript?

If I'm going to spend any time on this repo, might as well bring it up to 2023 standards.

**Comment by tomarad** [comment]
Yes, for sure.

**Comment by gamedevsam** [comment]
PR https://github.com/tomarad/JSON-Schema-Instantiator/pull/36 closes this issue.

**Comment by tomarad** [comment]
#36 merged.
