### ISSUE TITLE
add support for enums

### ISSUE THREAD

**Issue by jaroklima** [tomarad/JSON-Schema-Instantiator#8]
Hi.. I have added support for enums... if you give me the permission, I'll create a pull request.

**Comment by tomarad** [comment]
Hey, 
Please fork the repository and create a PR with your additions. 

Tom

**Comment by jaroklima** [comment]
https://github.com/tomarad/JSON-Schema-Instantiator/pull/9

**Comment by tomarad** [comment]
Merged & Closed.

**Comment by jaroklima** [comment]
thank you
